apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    name: db-pod
    app: voting-app-ass4
spec:
  containers:
    - name: db
      image: postgres:9.4
      ports:
        - containerPort: 5432
      envFrom:
        - secretRef:
                name: db-secret
