apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db
    app: voting-app-ass4
spec:
  selector:
    name: db-pod
    app: voting-app-ass4
  ports:
    - port: 5432
      targetPort: 5432

