apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
    app: voting-app-ass4
spec:
  selector:
    name: redis-pod
    app: voting-app-ass4
  ports:
    - port: 6379
      targetPort: 6379
